source ~/.bash_files/paths

# rvm-install added line:
if [[ -s ~/.rvm/scripts/rvm ]] ; then source ~/.rvm/scripts/rvm ; fi

source ~/.bash_files/aliases
test -s ~/.alias && . ~/.alias || true
[[ -f "/home/tris/.config/autopackage/paths-bash" ]] && . "/home/tris/.config/autopackage/paths-bash"

export PAGER='less -R'

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
