filetype on
filetype off
call pathogen#runtime_append_all_bundles()

filetype plugin indent on
set term=linux
set nocompatible " vim not vi mode
syntax on " Turn on syntax highlighting
set wildmode=longest,list " Set compleation mode
set hidden " keep files open when switching buffers
set autoindent " Auto indenting
set expandtab " Convert tabs to spaces
set shiftwidth=2 " Number of sapce to auto indent
set smarttab
set list listchars=tab:»·,trail:· " show tabs and trailing whitespace
set scrolloff=3 " Keep the cursor 3 lines away from the edge
set ruler " Show cursor position in status bar
set showmatch " Highlight matching brackets
set statusline=%<\ %n:%f\ %m%r%y%{&ff=='unix'?'':'\['.&ff.']'}%*%=%{SyntasticStatuslineFlag()}\ %-14.(%l,%c%V\ (%P)%)
set laststatus=2 " Show 2 lines of status

